"""Added settings

Revision ID: 01d99d6cdc0c
Revises: 79aef8eabcf6
Create Date: 2024-03-17 12:25:26.757159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d99d6cdc0c'
down_revision: Union[str, None] = '79aef8eabcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('Superadmin', 'GroupAdmin', 'GroupModerator', name='settingtype'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Setting_chat_id'), 'Setting', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Setting_chat_id'), table_name='Setting')
    op.drop_table('Setting')
    # ### end Alembic commands ###
