"""InitMigration

Revision ID: 79aef8eabcf6
Revises: 
Create Date: 2024-03-17 10:27:10.204382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79aef8eabcf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('personal_score', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('birthday_date', sa.DateTime(), nullable=True),
    sa.Column('house_type', sa.Integer(), nullable=True),
    sa.Column('house_reroll', sa.Integer(), nullable=True),
    sa.Column('messages_count', sa.BigInteger(), nullable=True),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_users_chat_id'), 'chat_users', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_users_user_id'), 'chat_users', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('System', 'Dictionary', 'NextBirthday', 'SaveBirthday', 'DeleteBirthday', 'ScheduledOneBirthday', 'ScheduledMultiBirthdays', 'BirthdayToday', 'ListOfBirthdays', 'Prophecy', 'Prophecy8Ball', name='texttype'), nullable=True),
    sa.Column('media', sa.String(length=5000), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_users_user_id'), table_name='chat_users')
    op.drop_index(op.f('ix_chat_users_chat_id'), table_name='chat_users')
    op.drop_table('chat_users')
    # ### end Alembic commands ###
